/* eslint-disable @typescript-eslint/no-misused-promises */
import type { GetServerSidePropsContext, NextPage } from "next";
import Head from "next/head";
import { getSession, signIn } from "next-auth/react";
import SigninIcon from "../components/Icons/SigninIcon";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>YouDoIt</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex h-screen flex-col items-center justify-center bg-gradient-to-b from-danube-200 to-danube-600 text-center">
        <h1 className="bg-gradient-to-t from-danube-900 via-danube-700 to-violet-800 bg-clip-text text-6xl font-black text-transparent underline sm:text-7xl md:text-8xl lg:text-9xl">
          YouDoIt
        </h1>

        <h2 className="my-16 max-w-md text-5xl font-black text-danube-800 sm:max-w-xl sm:text-6xl md:max-w-2xl md:text-7xl lg:max-w-4xl lg:text-8xl xl:max-w-7xl">
          Keep track of your <span className="text-blue-600">tasks </span>
          <em className="bg-gradient-to-r from-danube-800 to-violet-700 bg-clip-text text-transparent">
            and get things done
          </em>
        </h2>

        <button
          onClick={() => signIn("google")}
          className="flex items-center gap-3 rounded-full bg-white/60 py-3 px-6 text-xl font-bold text-danube-800 transition hover:bg-white/80"
        >
          <span> Sign in with Google</span> <SigninIcon />
        </button>
      </main>
    </>
  );
};

export const getServerSideProps = async (
  context: GetServerSidePropsContext
) => {
  const session = await getSession(context);

  if (session) {
    return {
      redirect: {
        destination: "/tasks",
        permanent: false,
      },
    };
  }

  return {
    props: {
      session,
    },
  };
};

export default Home;
