/* eslint-disable @typescript-eslint/no-misused-promises */
import type { GetServerSidePropsContext, NextPage } from "next";
import Head from "next/head";
import { getSession, signIn } from "next-auth/react";

// <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 "></div>

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Just Do It</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex h-screen flex-col items-center justify-center gap-8 bg-gradient-to-b from-danube-200 to-danube-600">
        <h1 className="text">JUST DO IT</h1>
        <h2></h2>
        <button
          onClick={() => signIn("google")}
          className="rounded-full bg-black/10 py-3 px-9 font-semibold transition hover:bg-black/20"
        >
          Sign in with Google
        </button>
      </main>
    </>
  );
};

/*
export const getServerSideProps = async (
  context: GetServerSidePropsContext
) => {
  const session = await getSession(context);

  if (session) {
    return {
      redirect: {
        destination: "/tasks",
        permanent: false,
      },
    };
  }

  return {
    props: {
      session,
    },
  };
};
*/
export default Home;
