/* eslint-disable react-hooks/rules-of-hooks */
import type { GetServerSidePropsContext, NextPage } from "next";
import { getSession, useSession } from "next-auth/react";
import Head from "next/head";

const tasks: NextPage = () => {
  const { data: session } = useSession();

  if (session)
    return (
      <>
        <Head>
          <title>YouDoIt | Tasks</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className="flex h-screen flex-col items-center justify-center gap-8 bg-danube-200">
          <div className="mt-8 h-4/5 w-4/5 max-w-5xl rounded-xl bg-white px-6 pt-4 pb-8 shadow-lg shadow-black/50 xl:mt-0">
            <div className="flex h-10 items-center justify-between">
              <h1 className="text-2xl font-bold text-danube-900">Your tasks</h1>
              <button className="rounded-lg bg-danube-500 px-6 py-2 font-semibold text-white transition hover:bg-danube-600">
                Add task
              </button>
            </div>
            <ul className="mt-10 flex h-5/6 w-full flex-col gap-2 overflow-x-hidden overflow-y-scroll px-4 text-lg font-medium">
              <li>Learn Next</li>
              <li>Learn Next</li>
            </ul>
          </div>
        </main>
      </>
    );
  return <p>Must be signed in</p>;
};

export const getServerSideProps = async (
  context: GetServerSidePropsContext
) => {
  const session = await getSession(context);

  if (!session) {
    return {
      redirect: {
        destination: "/",
        permanent: false,
      },
    };
  }

  return {
    props: {
      session,
    },
  };
};

export default tasks;
